- id: outside_lights_off_at_night
  alias: Outside Lights Off
  trigger:
    platform: time
    at: 00:30:00
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.entrance_light
  - service: switch.turn_off
    data:
      entity_id: switch.garden_spots
  - service: switch.turn_off
    data:
      entity_id: switch.parking_light

- id: darken_the_room_when_kodi_plays
  alias: Turn off kitchen lights when Kodi is playing
  trigger:
  - entity_id: media_player.living_room_kodi
    platform: state
    to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.kitchen_off
    - service: scene.turn_on
      data:
        entity_id: switch.living_room_off
    - service: switch.turn_on
      data:
        entity_id: switch.dining_table_light
