- id: parking_light_on_at_sunset
  initial_state: on
  alias: Parking light on at sunset
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  action:
  - data:
      entity_id: light.parking_light
    entity_id: light.parking_light
    service: light.turn_on
- id: outside_lights_off_at_night
  initial_state: on
  alias: Outside Lights Off
  trigger:
    platform: time
    at: 01:30:00
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - service: light.turn_off
    data:
      entity_id: light.entrance_light
  - service: light.turn_off
    data:
      entity_id: light.garden_spots
  - service: light.turn_off
    data:
      entity_id: light.parking_light
- id: darken_the_room_when_kodi_plays
  alias: Turn off kitchen lights when Kodi is playing
  initial_state: on
  trigger:
  - entity_id: media_player.living_room_kodi
    platform: state
    to: playing
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: binary_sensor.motion_sensor_158d0001e1876f
    state: 'off'
    for: 00:00:05
  action:
  - data:
      entity_id: light.dining_table_light
    service: switch.turn_on
  - data:
      entity_id: scene.kitchen_off
    service: scene.turn_on
  - data:
      entity_id: switch.living_room_off
    service: scene.turn_on
  - delay: 00:00:35
  - data:
      entity_id: cover.kitchen_blinds
    service: cover.close_cover
- id: white_room_light_off
  alias: White Room Light Off
  initial_state: on
  trigger:
  - entity_id: binary_sensor.0x00158d000233e86d_occupancy
    for: 00:30:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.white_room_light
    service: light.turn_off
- id: white_room_light_on
  alias: White Room Light On
  initial_state: on
  trigger:
  - entity_id: binary_sensor.0x00158d000233e86d_occupancy
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.white_room_light
    service: light.turn_on
- id: '1539154185148'
  alias: Wake UP
  trigger:
  - at: 06:30
    platform: time
  condition: []
  action:
  - service: media_player.media_play
    data:
      entity_id: media_player.googlehome9043
      media_content_id: https://actions.google.com/sounds/v1/alarms/phone_alerts_and_rings.ogg
      media_content_type: audio/mp3
- id: kitchen_lights_on_in_the_morning
  initial_state: on
  alias: Kitchen Lights On In The Morning
  trigger:
  - entity_id: binary_sensor.0x00158d0001e1876f_occupancy
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: 05:30
    before: 07:00
    condition: time
  action:
  - data:
      entity_id: scene.kitchen_on
    service: scene.turn_on
- id: '1540815898111'
  initial_state: on
  alias: Run Roomba on weekdays
  trigger:
  - at: '11:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - data:
      entity_id: switch.roomba
    service: switch.turn_on
- id: blanket_on_at_19_00
  initial_state: on
  alias: blanket on at 19:00
  trigger:
  - at: '19:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.blanket
    service: switch.turn_on
- id: arm_home_mode_at_12
  initial_state: on
  alias: Alarm on at 12
  trigger:
  - at: '23:59'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.alarm_home
    service: switch.turn_on
- id: blanket_off_at_19_00
  initial_state: on
  alias: blanket off at 23:00
  trigger:
  - at: 00:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.blanket
    service: switch.turn_off
- id: toilet_light_on
  initial_state: on
  alias: Toilet light on
  trigger:
  - entity_id: binary_sensor.0x00158d0002b7e9d3_occupancy
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.toilet_light
    service: light.turn_on
- id: toilet_light_off
  initial_state: on
  alias: Toilet light off
  trigger:
  - entity_id: binary_sensor.0x00158d0002b7e9d3_occupancy
    to: 'off'
    platform: state
    for: 00:30:00
  condition: []
  action:
  - data:
      entity_id: light.toilet_light
    service: light.turn_off
