- platform: template
  sensors:
    bedroom_ac_power_binary:
      friendly_name: "BedroomAC"
      value_template: "{{ states('sensor.bedroom_ac_power')|float > 2.5 }}"
    tamir_ac_power_binary:
      friendly_name: "TamirAC"  
      value_template: "{{ states('sensor.tamir_ac_power')  |float > 2.5 }}"
    girls_ac_power_binary:
      friendly_name: "GirlsAC"
      value_template: "{{ states('sensor.girls_ac_power')  |float > 2.5 }}"   

