
- platform: smartir
  name: AC
  unique_id: AC
  device_code: 1340
  controller_send_service: switch.broadlink_send_packet_192_168_0_124
  temperature_sensor: sensor.fireplace_rm2pro_temperature

- platform: smartir
  name: bedroom_ac
  unique_id: bedroom_ac
  device_code: 1180
  controller_send_service: switch.broadlink_send_packet_192_168_0_122
  temperature_sensor: sensor.bedroom_rm2pro_temperature
  power_sensor: binary_sensor.bedroom_ac_power_binary
  
- platform: smartir
  name: girls_ac
  unique_id: girls_ac
  device_code: 1180
  controller_send_service: switch.broadlink_send_packet_192_168_0_125
  temperature_sensor: sensor.girls_room_temp
  power_sensor: binary_sensor.girls_ac_power_binary
  
- platform: smartir
  name: tamir_ac
  unique_id: tamir_ac
  device_code: 1180
  controller_send_service: switch.broadlink_send_packet_192_168_0_124
  power_sensor: binary_sensor.tamir_ac_power_binary

