- platform: broadlink
  name: TV
  host: 192.168.0.112
  mac: '34:EA:34:42:A9:6F'    
  ircodes_ini: 'broadlink_media_codes/yes_lg.ini'
- platform: kodi
  name: living_room_kodi
  host: 192.168.0.133
- platform: kodi
  name: bedroom_kodi
  host: 192.168.0.104
