- platform: broadlink
  name: fireplace_rm2pro
  host: 192.168.0.124
  mac: '34:EA:34:B5:46:61'  
  monitored_conditions:
    - 'temperature'

- platform: broadlink
  name: bedroom_rm2pro
  host: 192.168.0.122
  mac: '34:EA:34:C7:31:F9'
  monitored_conditions:
    - 'temperature'

#- platform: broadlinkpower
#  name: bedroom_blanket_power
#  host: 192.168.0.138
#  mac: '34:EA:34:B5:46:61'

- platform: mqtt
  name: tamir_ac_power
  state_topic: "tele/tamir/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"

- platform: mqtt
  name: girls_ac_power
  state_topic: "tele/girls/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"

- platform: mqtt
  name: bedroom_ac_power
  state_topic: 'tele/bedroom/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"

- platform: mqtt
  name: roman_0               
  state_topic: 'monitor/presense-1/D0:C5:F3:54:33:AF'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: "%"
  name: 'Roman 0'

- platform: mqtt
  name: dina_0
  state_topic: 'monitor/presense-1/14:BD:61:B0:9D:D0'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: "%"
  name: 'Dina 0'

- platform: mqtt
  name: mika_0
  state_topic: 'monitor/presense-1/38:E6:0A:3C:05:5D'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: "%"
  name: 'Mika 0'

- platform: mqtt
  name: lia_0
  state_topic: 'monitor/presense-1/78:02:F8:D6:1A:9F'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: "%"
  name: 'Lia 0'

- platform: mqtt
  name: tamir_0
  state_topic: 'monitor/presense-1/EC:D0:9F:DE:CA:B6'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: "%"
  name: 'Tamir 0'

- platform: mqtt
  name: roman_1               
  state_topic: 'monitor/presense-2/D0:C5:F3:54:33:AF'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: "%"
  name: 'Roman 1'

- platform: mqtt
  name: dina_1
  state_topic: 'monitor/presense-2/14:BD:61:B0:9D:D0'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: "%"
  name: 'Dina 1'

- platform: mqtt
  name: mika_1
  state_topic: 'monitor/presense-2/38:E6:0A:3C:05:5D'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: "%"
  name: 'Mika 1'

- platform: mqtt
  name: lia_1
  state_topic: 'monitor/presense-2/78:02:F8:D6:1A:9F'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: "%"
  name: 'Lia 1'

- platform: mqtt
  name: tamir_1
  state_topic: 'monitor/presense-2/EC:D0:9F:DE:CA:B6'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: "%"
  name: 'Tamir 1'

- platform: min_max
  name: Tamir
  type: max
  round_digits: 0
  entity_ids:
    - sensor.tamir_0
    - sensor.tamir_1

- platform: min_max
  name: Lia
  type: max
  round_digits: 0
  entity_ids:
    - sensor.lia_0
    - sensor.lia_1  

- platform: min_max
  name: Mika
  type: max
  round_digits: 0
  entity_ids:
    - sensor.mika_0
    - sensor.mika_1 

- platform: min_max
  name: Dina
  type: max
  round_digits: 0
  entity_ids:
    - sensor.dina_0
    - sensor.dina_1  

- platform: min_max
  name: Roman
  type: max
  round_digits: 0
  entity_ids:
    - sensor.roman_0
    - sensor.roman_1

- platform: template
  sensors:
    bedroom_tv:
      friendly_name: "Bedroom TV"
      value_template: "{{ is_state('media_player.bedroom_tv', 'on') and is_state('binary_sensor.bedroom_tv', 'on') }}"
