#!/bin/bash

b1="sudo /home/homeassistant/.homeassistant/shell_scripts/switchbot_py3.py -d D4:71:B0:1E:43:86"
b2="sudo /home/homeassistant/.homeassistant/shell_scripts/switchbot_py3.py -d C5:32:61:21:D0:B0"

$b2
$b1
$b2
$b1

